[
  { "base": "run", "third_person": "runs", "gerund": "running", "past": "ran", "stative": false },
  { "base": "love", "third_person": "loves", "gerund": "loving", "past": "loved", "stative": true },
  { "base": "write", "third_person": "writes", "gerund": "writing", "past": "wrote", "stative": false },
  { "base": "sit", "third_person": "sits", "gerund": "sitting", "past": "sat", "stative": false },
  { "base": "jump", "third_person": "jumps", "gerund": "jumping", "past": "jumped", "stative": false },
  { "base": "walk", "third_person": "walks", "gerund": "walking", "past": "walked", "stative": false },
  { "base": "be", "third_person": "is", "gerund": "being", "past": "was", "stative": true },
  { "base": "go", "third_person": "goes", "gerund": "going", "past": "went", "stative": false },
  { "base": "do", "third_person": "does", "gerund": "doing", "past": "did", "stative": false },
  { "base": "take", "third_person": "takes", "gerund": "taking", "past": "took", "stative": false },
  { "base": "make", "third_person": "makes", "gerund": "making", "past": "made", "stative": false },
  { "base": "get", "third_person": "gets", "gerund": "getting", "past": "got", "stative": false },
  { "base": "come", "third_person": "comes", "gerund": "coming", "past": "came", "stative": false },
  { "base": "think", "third_person": "thinks", "gerund": "thinking", "past": "thought", "stative": true },
  { "base": "know", "third_person": "knows", "gerund": "knowing", "past": "knew", "stative": true },
  { "base": "believe", "third_person": "believes", "gerund": "believing", "past": "believed", "stative": true },
  { "base": "understand", "third_person": "understands", "gerund": "understanding", "past": "understood", "stative": true },
  { "base": "hate", "third_person": "hates", "gerund": "hating", "past": "hated", "stative": true },
  { "base": "own", "third_person": "owns", "gerund": "owning", "past": "owned", "stative": true },
  { "base": "want", "third_person": "wants", "gerund": "wanting", "past": "wanted", "stative": true },
  { "base": "need", "third_person": "needs", "gerund": "needing", "past": "needed", "stative": true },
  { "base": "appear", "third_person": "appears", "gerund": "appearing", "past": "appeared", "stative": true },
  { "base": "seem", "third_person": "seems", "gerund": "seeming", "past": "seemed", "stative": true },
  { "base": "prefer", "third_person": "prefers", "gerund": "preferring", "past": "preferred", "stative": true },
  { "base": "belong", "third_person": "belongs", "gerund": "belonging", "past": "belonged", "stative": true },
  { "base": "contain", "third_person": "contains", "gerund": "containing", "past": "contained", "stative": true },
  { "base": "include", "third_person": "includes", "gerund": "including", "past": "included", "stative": true },
  { "base": "resemble", "third_person": "resembles", "gerund": "resembling", "past": "resembled", "stative": true },
  { "base": "mean", "third_person": "means", "gerund": "meaning", "past": "meant", "stative": true },
  { "base": "remember", "third_person": "remembers", "gerund": "remembering", "past": "remembered", "stative": true },
  { "base": "cut", "third_person": "cuts", "gerund": "cutting", "past": "cut", "stative": false },
  { "base": "hop", "third_person": "hops", "gerund": "hopping", "past": "hopped", "stative": false },
  { "base": "hug", "third_person": "hugs", "gerund": "hugging", "past": "hugged", "stative": false },
  { "base": "slip", "third_person": "slips", "gerund": "slipping", "past": "slipped", "stative": false },
  { "base": "tap", "third_person": "taps", "gerund": "tapping", "past": "tapped", "stative": false },
  { "base": "bet", "third_person": "bets", "gerund": "betting", "past": "bet", "stative": false },
  { "base": "fit", "third_person": "fits", "gerund": "fitting", "past": "fitted", "stative": false },
  { "base": "win", "third_person": "wins", "gerund": "winning", "past": "won", "stative": false },
  { "base": "let", "third_person": "lets", "gerund": "letting", "past": "let", "stative": false },
  { "base": "dig", "third_person": "digs", "gerund": "digging", "past": "dug", "stative": false },
  { "base": "rub", "third_person": "rubs", "gerund": "rubbing", "past": "rubbed", "stative": false },
  { "base": "rip", "third_person": "rips", "gerund": "ripping", "past": "ripped", "stative": false },
  { "base": "pin", "third_person": "pins", "gerund": "pinning", "past": "pinned", "stative": false },
  { "base": "tag", "third_person": "tags", "gerund": "tagging", "past": "tagged", "stative": false },
  { "base": "hit", "third_person": "hits", "gerund": "hitting", "past": "hit", "stative": false },
  { "base": "sum", "third_person": "sums", "gerund": "summing", "past": "summed", "stative": false },
  { "base": "nod", "third_person": "nods", "gerund": "nodding", "past": "nodded", "stative": false },
  { "base": "pat", "third_person": "pats", "gerund": "patting", "past": "patted", "stative": false },
  { "base": "play", "third_person": "plays", "gerund": "playing", "past": "played", "stative": false },
  { "base": "work", "third_person": "works", "gerund": "working", "past": "worked", "stative": false },
  { "base": "talk", "third_person": "talks", "gerund": "talking", "past": "talked", "stative": false },
  { "base": "listen", "third_person": "listens", "gerund": "listening", "past": "listened", "stative": false },
  { "base": "watch", "third_person": "watches", "gerund": "watching", "past": "watched", "stative": false },
  { "base": "move", "third_person": "moves", "gerund": "moving", "past": "moved", "stative": false },
  { "base": "plan", "third_person": "plans", "gerund": "planning", "past": "planned", "stative": false },
  { "base": "push", "third_person": "pushes", "gerund": "pushing", "past": "pushed", "stative": false },
  { "base": "close", "third_person": "closes", "gerund": "closing", "past": "closed", "stative": false },
  { "base": "ask", "third_person": "asks", "gerund": "asking", "past": "asked", "stative": false },
  { "base": "open", "third_person": "opens", "gerund": "opening", "past": "opened", "stative": false },
  { "base": "live", "third_person": "lives", "gerund": "living", "past": "lived", "stative": false },
  { "base": "start", "third_person": "starts", "gerund": "starting", "past": "started", "stative": false },
  { "base": "try", "third_person": "tries", "gerund": "trying", "past": "tried", "stative": false },
  { "base": "laugh", "third_person": "laughs", "gerund": "laughing", "past": "laughed", "stative": false },
  { "base": "cry", "third_person": "cries", "gerund": "crying", "past": "cried", "stative": false },
  { "base": "travel", "third_person": "travels", "gerund": "traveling", "past": "traveled", "stative": false },
  { "base": "visit", "third_person": "visits", "gerund": "visiting", "past": "visited", "stative": false },
  { "base": "bring", "third_person": "brings", "gerund": "bringing", "past": "brought", "stative": false },
  { "base": "buy", "third_person": "buys", "gerund": "buying", "past": "bought", "stative": false },
  { "base": "sing", "third_person": "sings", "gerund": "singing", "past": "sang", "stative": false },
  { "base": "drink", "third_person": "drinks", "gerund": "drinking", "past": "drank", "stative": false },
  { "base": "drive", "third_person": "drives", "gerund": "driving", "past": "drove", "stative": false },
  { "base": "see", "third_person": "sees", "gerund": "seeing", "past": "saw", "stative": false },
  { "base": "speak", "third_person": "speaks", "gerund": "speaking", "past": "spoke", "stative": false },
  { "base": "fly", "third_person": "flies", "gerund": "flying", "past": "flew", "stative": false },
  { "base": "stand", "third_person": "stands", "gerund": "standing", "past": "stood", "stative": false },
  { "base": "build", "third_person": "builds", "gerund": "building", "past": "built", "stative": false },
  { "base": "break", "third_person": "breaks", "gerund": "breaking", "past": "broke", "stative": false },
  { "base": "hold", "third_person": "holds", "gerund": "holding", "past": "held", "stative": false },
  { "base": "swim", "third_person": "swims", "gerund": "swimming", "past": "swam", "stative": false },
  { "base": "give up", "third_person": "gives up", "gerund": "giving up", "past": "gave up", "stative": false },
  { "base": "take off", "third_person": "takes off", "gerund": "taking off", "past": "took off", "stative": false },
  { "base": "look after", "third_person": "looks after", "gerund": "looking after", "past": "looked after", "stative": false },
  { "base": "break down", "third_person": "breaks down", "gerund": "breaking down", "past": "broke down", "stative": false },
  { "base": "run out", "third_person": "runs out", "gerund": "running out", "past": "ran out", "stative": false },
  { "base": "put up with", "third_person": "puts up with", "gerund": "putting up with", "past": "put up with", "stative": false },
  { "base": "bring up", "third_person": "brings up", "gerund": "bringing up", "past": "brought up", "stative": false },
  { "base": "look forward to", "third_person": "looks forward to", "gerund": "looking forward to", "past": "looked forward to", "stative": false },
  { "base": "set off", "third_person": "sets off", "gerund": "setting off", "past": "set off", "stative": false },
  { "base": "come across", "third_person": "comes across", "gerund": "coming across", "past": "came across", "stative": false },
  { "base": "call off", "third_person": "calls off", "gerund": "calling off", "past": "called off", "stative": false },
  { "base": "turn up", "third_person": "turns up", "gerund": "turning up", "past": "turned up", "stative": false },
  { "base": "pick up", "third_person": "picks up", "gerund": "picking up", "past": "picked up", "stative": false },
  { "base": "hold on", "third_person": "holds on", "gerund": "holding on", "past": "held on", "stative": false },
  { "base": "get away with", "third_person": "gets away with", "gerund": "getting away with", "past": "got away with", "stative": false },
  { "base": "put off", "third_person": "puts off", "gerund": "putting off", "past": "put off", "stative": false },
  { "base": "back up", "third_person": "backs up", "gerund": "backing up", "past": "backed up", "stative": false },
  { "base": "break up", "third_person": "breaks up", "gerund": "breaking up", "past": "broke up", "stative": false },
  { "base": "fall apart", "third_person": "falls apart", "gerund": "falling apart", "past": "fell apart", "stative": false },
  { "base": "keep up", "third_person": "keeps up", "gerund": "keeping up", "past": "kept up", "stative": false },
  { "base": "limit", "third_person": "limits", "gerund": "limiting", "past": "limited", "stative": false },
  { "base": "benefit", "third_person": "benefits", "gerund": "benefiting", "past": "benefited", "stative": false },
  { "base": "enter", "third_person": "enters", "gerund": "entering", "past": "entered", "stative": false },
  { "base": "develop", "third_person": "develops", "gerund": "developing", "past": "developed", "stative": false },
  { "base": "control", "third_person": "controls", "gerund": "controlling", "past": "controlled", "stative": false },
  { "base": "credit", "third_person": "credits", "gerund": "crediting", "past": "credited", "stative": false },
  { "base": "offer", "third_person": "offers", "gerund": "offering", "past": "offered", "stative": false },
  { "base": "profit", "third_person": "profits", "gerund": "profiting", "past": "profited", "stative": false }
]
